### ISSUE TITLE
[Nice to have] Better style for MultiLine title

### ISSUE THREAD

**Issue by VincentLanglet** [foucdeg/scrummer#5]
![style](https://cloud.githubusercontent.com/assets/9052536/25434213/bfaca32e-2a8b-11e7-8216-cd09c2f27321.png)

**Comment by foucdeg** [comment]
@VincentLanglet thanks! But I can't seem to reproduce:

![image](https://cloud.githubusercontent.com/assets/12948989/25434631/4eea085a-2a8d-11e7-97ec-9dbd97650c6a.png)

Do you have any Stylus styles applied?

**Comment by VincentLanglet** [comment]
Indeed ! I will look how to solve my conflict. Thanks !
