### ISSUE TITLE
List totals display - but nothing else (Fx 55 / 57)

### ISSUE THREAD

**Issue by bunnybooboo** [foucdeg/scrummer#9]
Installed ScrummerTheodo (in Firefox 55.0.2 and Firefox Nightly 57 [2017-08-21]). Totals show at the top of each list, but there is no further changes to my Trello board. 

![screenshot from 2017-08-21 16-16-59](https://user-images.githubusercontent.com/5793295/29526157-c70f0640-868c-11e7-96bf-1af026ca80ee.png)

If I click a card there is no numbers or option for scrummer anywhere.

![screenshot from 2017-08-21 16-23-03](https://user-images.githubusercontent.com/5793295/29526262-189c06d4-868d-11e7-9744-d56741c9041d.png)

I then added legacy add-on Scrummer in Firefox 55, and behaviour is essentially the same.
![screenshot from 2017-08-21 16-24-37](https://user-images.githubusercontent.com/5793295/29526343-540b8e7e-868d-11e7-9790-280bd332cb92.png)
![screenshot from 2017-08-21 16-25-44](https://user-images.githubusercontent.com/5793295/29526375-70261ea8-868d-11e7-8366-67eee5726984.png)

**Comment by pierpo** [comment]
@bunnybooboo You have to edit the title :wink:

**Comment by bunnybooboo** [comment]
@pierpo do you mean in Trello, or the title of this issue for clarity?

**Comment by pierpo** [comment]
@bunnybooboo I meant in Trello. The buttons are not displayed until you click the title of your card for edition.

But I'm probably wrong, I guess you've done that already!

**Comment by bunnybooboo** [comment]
ahhhh I get you. That was not intuitive for my brain today. Thanks @pierpo

**Comment by pierpo** [comment]
@bunnybooboo You're welcome, glad I could help :wink:
